package de.gamedots.mindlr.mindlrfrontend.models;

import java.util.Date;

/**
 * Created by max on 26.09.15.
 * Type of post that is used when a new post is generated by the user
 */
public class SubmitPost {

    private long userID;
    private Date submitDate;
    private String contentText;
    private int categoryID; //TODO: Create Category Class to represent DB table

    public SubmitPost(long userID, Date submitDate, String contentText, int categoryID) {
        this.userID = userID;
        this.submitDate = submitDate;
        this.contentText = contentText;
        this.categoryID = categoryID;
    }

    public long getUserID() {
        return userID;
    }

    public Date getSubmitDate() {
        return submitDate;
    }

    public int getCategoryID() {
        return categoryID;
    }

    public String getContentText() {
        return contentText;
    }
}
