package de.gamedots.mindlr.mindlrfrontend.model.post;

import java.util.Date;

import de.gamedots.mindlr.mindlrfrontend.model.Category;

/**
 * Created by max on 26.09.15.
 * Type of post that is used when a new post is generated by the user
 */
public class SubmitPost {

    private long userID;
    private Date submitDate;
    private String contentText;
    private Category category; //TODO: Create Category Class to represent DB table

    public SubmitPost(long userID, Date submitDate, String contentText, Category category) {
        this.userID = userID;
        this.submitDate = submitDate;
        this.contentText = contentText;
        this.category = category;
    }

    public long getUserID() {
        return userID;
    }

    public Date getSubmitDate() {
        return submitDate;
    }

    public Category getCategory() {
        return category;
    }

    public String getContentText() {
        return contentText;
    }
}
